//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base64Guid {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Base64Guid {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Base64Guid() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Base64Guid.Base64Guid", typeof(Base64Guid).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert GUID &lt;&gt; Base64GUID.
        /// </summary>
        internal static string AccessibleName {
            get {
                return ResourceManager.GetString("AccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base 64 GUID.
        /// </summary>
        internal static string Base64GuidText {
            get {
                return ResourceManager.GetString("Base64GuidText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUID.
        /// </summary>
        internal static string GuidText {
            get {
                return ResourceManager.GetString("GuidText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HelloWorldLabel.
        /// </summary>
        internal static string HelloWorldLabel {
            get {
                return ResourceManager.GetString("HelloWorldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert GUID &lt;&gt; Base64GUID.
        /// </summary>
        internal static string LongDisplayTitle {
            get {
                return ResourceManager.GetString("LongDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base 64 GUID.
        /// </summary>
        internal static string ShortDisplayTitle {
            get {
                return ResourceManager.GetString("ShortDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base 64 GUID ⬇.
        /// </summary>
        internal static string ToBase64Guid {
            get {
                return ResourceManager.GetString("ToBase64Guid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⬆ GUID.
        /// </summary>
        internal static string ToGuid {
            get {
                return ResourceManager.GetString("ToGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trim trailing == from base 64 representation.
        /// </summary>
        internal static string TrimPaddingDescription {
            get {
                return ResourceManager.GetString("TrimPaddingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trim ==.
        /// </summary>
        internal static string TrimPaddingTitle {
            get {
                return ResourceManager.GetString("TrimPaddingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap + with - and / with _ to make url safe.
        /// </summary>
        internal static string UrlSafeDescription {
            get {
                return ResourceManager.GetString("UrlSafeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url Safe.
        /// </summary>
        internal static string UrlSafeTitle {
            get {
                return ResourceManager.GetString("UrlSafeTitle", resourceCulture);
            }
        }
    }
}
